/*
 * action types
 */
export const UPDATE_DOCUMENTS_FROM_DATABASE = 'UPDATE_DOCUMENTS_FROM_DATABASE'
export const ADD_DEVICE_TOKEN = 'ADD_DEVICE_TOKEN'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const UPDATE_LIST = 'UPDATE_LIST'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS'
export const UPDATE_SCALE = 'UPDATE_SCALE'
export const DELETE_LIST = 'DELETE_LIST'
export const DELETE_ALL_DATA = 'DELETE_ALL_DATA'
export const CLEAR_STORE = 'CLEAR_STORE'
export const SCREEN_SET_SELECTED_ITEMS = 'SCREEN_SET_SELECTED_ITEMS'
export const SCREEN_ADD_SELECTED_ITEM = 'SCREEN_ADD_SELECTED_ITEM'
export const SCREEN_REMOVE_SELECTED_ITEM = 'SCREEN_REMOVE_SELECTED_ITEM'
export const SCREEN_SET_ITEM_SELECTION_MODE = 'SCREEN_SET_ITEM_SELECTION_MODE'
export const SCREEN_SET_ITEM_FILTER_MODE = 'SCREEN_SET_ITEM_FILTER_MODE'
export const SCREEN_SET_ITEM_FILTER_CRITERIA = 'SCREEN_SET_ITEM_FILTER_CRITERIA'
export const SCREEN_LISTDETAILS_SET_ITEM_SORTING_MANNER =
  'SCREEN_LISTDETAILS_SET_ITEM_SORTING_MANNER'
export const SCREEN_LISTDETAILS_SET_ITEM_SORT_MODE =
  'SCREEN_LISTDETAILS_SET_ITEM_SORT_MODE'
export const SCREEN_COLLECTIONSOVERVIEW_SET_LIST_SORTING_MANNER =
  'SCREEN_COLLECTIONSOVERVIEW_SET_LIST_SORTING_MANNER'
export const SCREEN_COLLECTIONSOVERVIEW_SET_LIST_SORT_MODE =
  'SCREEN_COLLECTIONSOVERVIEW_SET_LIST_SORT_MODE'
export const SCREEN_SHARE_ITEM_SET_CONTACTS = 'SCREEN_SHARE_ITEM_SET_CONTACTS'

// web version constants

export const AUTH_SUCCES = 'AUTH_SUCCESS'
